name: MSVC Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: "utf-8"
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: _build
        setup-options: --fatal-meson-warnings
        options: --verbose
        meson-version: 0.54.3
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: msvc-ci
        path: _build/meson-logs/
